apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
      - image: nguyendanielt/authservice:latest
        name: authservice
        env:
        - name: CONNECTION_STRING
          value: "host=postgres-clusterip-svc user=postgres password=superuser dbname=usersdb port=5432 sslmode=disable TimeZone=America/New_York"
        - name: BOOTSTRAP_SERVER
          value: "kafka-cluster-kafka-bootstrap:9092"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: auth-clusterip-svc
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: authservice