apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: passwordservice
  template:
    metadata:
      labels:
        app: passwordservice
    spec:
      containers:
      - image: nguyendanielt/passwordservice:latest
        name: passwordservice
        env:
        - name: CONNECTION_STRING
          value: "host=postgres-clusterip-svc user=postgres password=superuser dbname=passwordsdb port=5432 sslmode=disable TimeZone=America/New_York"
        - name: AUTH_SERVICE_HOST
          value: "http://auth-clusterip-svc:8080"
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: password-clusterip-svc
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: passwordservice